### PR TITLE
ARR

### PR DESCRIPTION
**Pull request by valoeghese**
- 3 new documented events
- one adapted from one events, one adapted from a certain scientific mod, one adapted from epic valo mod.
- MIT licence
- mod id and stuff
- no test mod lol

### CODE REVIEW

**Comment by valoeghese** [comment]
Lol no reviews

**Comment by valoeghese** [comment]
I assume that means you approve

**Comment by valoeghese** [comment]
Yeet

**Review by sschr15 — COMMENTED** [review]
ok

**Pull request merged**
